version: '3.8'

services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - shared_secrets:/etc/nginx/secrets
    depends_on:
      encipher-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      ai-network:
        aliases:
          - api.your-domain.com

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile.ollama
      args:
        - MODEL=deepseek-r1:1.5b
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - ai-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  encipher-server:
    build:
      context: ./encipher-server
      dockerfile: Dockerfile.axum
    volumes:
      - shared_secrets:/secrets
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 3s
      retries: 10
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_HOST=ollama:11434
      - RUST_LOG=info
      - DATABASE_URL=postgres://user1:pass@postgres:5432/users
      - JWT_SECRET=secret
    networks:
      - ai-network

  test-client:
    build:
      context: ./client-test
      dockerfile: Dockerfile.client
    depends_on:
      nginx:
        condition: service_healthy
    networks:
      - ai-network
  
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: users
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge

volumes:
  ollama-data:
  shared_secrets:
  postgres-data: