FROM rust as builder
WORKDIR /usr/src/app

COPY . .

RUN cargo install --path .

FROM debian:bookworm-slim
RUN apt-get update && \
    apt-get install -y ca-certificates curl libssl-dev && \
    rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/src/app/target/release/client-test /usr/local/bin/client-test
CMD ["/usr/local/bin/client-test"]