[package]
name = "docugraph"
version = "0.1.0"
edition = "2024"

[dependencies]
indradb-lib = { version = "4.0.0", features = ["rocksdb-datastore"] }
rust-bert = { version = "0.23.0", features = ["download-libtorch"] }
