[package]
name = "docugraph"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.96"
indradb-lib = { version = "4.0.0", features = ["rocksdb-datastore"] }
kalosm = "0.4.0"
rust-bert = { version = "0.23.0", features = ["download-libtorch"] }
uuid = "1.14.0"
